### PR TITLE
add excel file support

### PR DESCRIPTION
**Pull request by all4one-max**
The following features have been added as per issue #5:
- downloading tabs in excel format (.xlsx)
- uploading and opening the tabs from an excel file

I have primarily used sheetJS package for implementing the features, so make sure to install all the dependencies. 

I hope these features are as desired.

### CODE REVIEW

**Comment by all4one-max** [comment]
@Jitensid don't we have to link the PR to the original issue#5. Also, everything is running correctly in my system. can you help me understand the errors shown here.

**Comment by Jitensid** [comment]
I checked your package.json file. Could you add the dependency like others ?

**Comment by all4one-max** [comment]
Doesn't package.json update automatically when we run npm install?

**Comment by Jitensid** [comment]
> Doesn't package.json update automatically when we run npm install?

It does but why it is in a different format?

**Comment by all4one-max** [comment]
> > Doesn't package.json update automatically when we run npm install?
> 
> It does but why it is in a different format?

What do you mean by different format? Are you not able to run it in your system?

**Comment by Jitensid** [comment]
Check review comments

**Comment by all4one-max** [comment]
In CI/test of windows and macOS, it says that lockfile version 1 is required but in the main branch also it says lockfile version 2 in package-lock.json.

**Comment by Jitensid** [comment]
Just remove the package.lock json file and try again . Ideally it should not be pushed to repo. 

It should work after that.

**Comment by all4one-max** [comment]
> Just remove the package.lock json file and try again . Ideally it should not be pushed to repo.
> 
> It should work after that.

So should I add it to gitignore and then push again?

**Comment by all4one-max** [comment]
image

image

@Jitensid It shows that the split method will have undefined, but it can never be since I am uploading a file. can you bypass the test and run it on your device once, all the functionalities are running correctly in my system.

**Comment by all4one-max** [comment]
@Jitensid Why does it always wait for approval to test after the initial PR approval?

**Comment by all4one-max** [comment]
@Jitensid there's some issue in the UploadButton.test.js as shown in the log, but I didn't even work on it.

yeah I will look into this.

**Comment by all4one-max** [comment]
@Jitensid I think so, the issue is due to the test being written for json file format and not compatible with other formats.

**Comment by Jitensid** [comment]
@all4one-max I am running the code into my system

**Comment by Jitensid** [comment]
I will need some time to figure out what exactly is the issue

**Comment by all4one-max** [comment]
@Jitensid I want to start working on the other issue while you figure out the problem we are facing here. But I was wondering if I make a separate branch and start working on it, won't it cause an issue when this PR gets merged? Like I will start working on the branch from the code i.e in the main branch.

nvm, I can't start working on it until this gets merged since both issues are to be handled in the upload Button file itself.

Hoping for a quick resolution!

**Comment by Jitensid** [comment]
> @Jitensid I want to start working on the other issue while you figure out the problem we are facing here. But I was wondering if I make a separate branch and start working on it, won't it cause an issue when this PR gets merged? Like I will start working on the branch from the code i.e in the main branch.
> 
> nvm, I can't start working on it until this gets merged since both issues are to be handled in the upload Button file itself.
> 
> Hoping for a quick resolution!
In which issue you are planning to work?

**Comment by all4one-max** [comment]
The other issue I raised, upload tab files options.

**Comment by Jitensid** [comment]
@all4one-max test is passing now.

**Comment by all4one-max** [comment]
@Jitensid how do I handle the codecov thing? wait! since you have made commits in the branch I will have to pull first right?

**Comment by Jitensid** [comment]
Yeah so the issue is code coverage has dropped. 
We have to write test cases for excel file upload as well. 
Yeah you have to pull the code.

**Comment by all4one-max** [comment]
> Yeah so the issue is code coverage has dropped. We have to write test cases for excel file upload as well. Yeah you have to pull the code.

hey will it help if I try to reduce code at some place (like write  a shorter version).

**Comment by Jitensid** [comment]
please revert your latest commit

**Comment by all4one-max** [comment]
okay!

**Comment by Jitensid** [comment]
I shall write the test for excel file upload in some time.

**Comment by Jitensid** [comment]
https://app.codecov.io/gh/Jitensid/TabPort/pull/22

This will show where your code is not covered by test cases

**Comment by all4one-max** [comment]
I see, but I don't know how to write test cases, I can try learning how but it might take a lot of time.

**Comment by Jitensid** [comment]
> I see, but I don't know how to write test cases, I can try learning how but it might take a lot of time.

No problem I shall write one for this case in some time.

**Comment by Jitensid** [comment]
@all4one-max thanks for your contribution and I loved your dedication !
Keep up the good work !

**Pull request merged**
