### PR TITLE
checkbox for uploaded tabs to open

### PR DESCRIPTION
**Pull request by all4one-max**
The following feature has been added as per the issue raised (#16):
- Upon uploading the tab files, user is prompted with the list of tabs in the file
- User can select what all tabs user wishes to open

### CODE REVIEW

**Comment by all4one-max** [comment]
@Jitensid I think so the tests are failing because they haven't been made to handle UploadTabsList things and passing props to the upload button.

**Comment by all4one-max** [comment]
@Jitensid I need help. I was trying to write test, I am stuck. Like after uploading I need to show the uploadTabsList, but for that when I write test, I am getting TestingLibraryELementError, for some reason it is not able to find element.

**Comment by Jitensid** [comment]
> @Jitensid I need help. I was trying to write test, I am stuck. Like after uploading I need to show the uploadTabsList, but for that when I write test, I am getting TestingLibraryELementError, for some reason it is not able to find element.

You can add **data-testid** property to the element you want to find in your tests.

**Comment by all4one-max** [comment]
image

see, hereafter the fireEvent.click() and the file upload thing, I thought that I will be able to access the checkbox in the UploadButtonTabsList page, but unfortunately, it is not reading it. ig it has to do something with upload dialog box taking time

**Comment by all4one-max** [comment]
@Jitensid I have added all the test files needed, I am missing the code coverage by very less. Please help me with this, it is almost done.

**Comment by all4one-max** [comment]
@Jitensid All tests have passed including the codecov/patch test with an 89.65% of diff hit (the target was 84.84%). Please merge the PR and let me know if everything is working fine.

**Comment by all4one-max** [comment]
@Jitensid Although everything is done, I had a doubt. When we call jest.spyOn(chrome.tabs, 'create').mockImplementation() we are creating a mock function. so I wanted to understand how things actually flow. like when I generate a fire event and click on the open tabs button, I will use chrome.tabs.create() to open the tabs, so does spyOn() mocks this particular call and uses the function it creates or is there something else to it?

**Comment by all4one-max** [comment]
@Jitensid Sorry to bother you again! But please merge my PR, I have to get it accepted also and if you merge it today, it will be accepted by 29th.

**Pull request merged**
